name = "statuspagestatuspage"
type = "javascript"
zone_id = ""
account_id = "49045c1d2a1b69c8b56063c60237a1a4"
route = ""
workers_dev = true
compatibility_date = "2021-12-08"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
