name = "statuspagestatuspage"
type = "javascript"
zone_id = ""
account_id = "49045c1d2a1b69c8b56063c60237a1a4"
route = ""
workers_dev = true
compatibility_date = "2021-12-08"

kv_namespaces = [
    { binding = "STATUS_KV", id = "9900fd876b4b4cc1afc90e68b0ff9382", preview_id = "9900fd876b4b4cc1afc90e68b0ff9382" }
]

[triggers]
crons = ["* * * * *"]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
